### ISSUE TITLE
assembly_procedure

### ISSUE THREAD

**Issue by mamtamasand** [macmanes-lab/Oyster_River_Protocol#13]
i have RNA seq datasets of samples containing single ended and paired ended reads. so what would i have to do in script so that all the dataset should assemble together.

**Comment by mamtamasand** [comment]
Thanks for the reply sir
I have 15 samples of RNA seq data and 2 samples of single ended reads so i
have to make full assembly of these 17 samplles together.

**Comment by macmanes** [comment]
ok, there is a strong recommendation against doing that - there are some details in the paper, but basically polymorphism breaks the assembler, resulting in a less contiguous assembly. Typically the rec. is to use 1 individual for assembly, or 1 per treatment (biological) group. Minimizing individuals is really important for assembly.
