### ISSUE TITLE
java memory issue

### ISSUE THREAD

**Issue by karenbobier** [macmanes-lab/Oyster_River_Protocol#14]
I am trying to assemble a transciptome on our cluster and am getting errors related to java memory:

java -Xmx10G -Xms1G -Xss1G   -XX:ParallelGCThreads=2  -jar /usr/loc
al/apps/gb/ORP/Oyster_River_Protocol/software/anaconda/install/envs/orp_v2/opt/tr
inity-2.8.4/Butterfly/Butterfly.jar -N 100000 -L 200 -F 500 -C /lustre1/keb27269/
noto/assemblies/noto_1.trinity/read_partitions/Fb_0/CBin_90/c9021.trinity.reads.f
a.out/chrysalis/Component_bins/Cbin0/c8.graph  --path_reinforcement_distance=25

I am running this job with 300GB mem and 16 threads. It looks like even though the job has access to 300GB of memory, Java is set to only use 10GB. 

Any ideas on how to fix this? 

Here are my output and error files:
[orp_noto1.3.out.txt](https://github.com/macmanes-lab/Oyster_River_Protocol/files/2590400/orp_noto1.3.out.txt)
[orp_noto1.3.err.txt](https://github.com/macmanes-lab/Oyster_River_Protocol/files/2590401/orp_noto1.3.err.txt)

Thanks!

**Comment by macmanes** [comment]
Hi Karen, 

This is an issue with Java, indeed. See 

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

This is an issue we used to see in older versions of Trinity, but up until recently, we (I) have not seen it. In the last few days, using Trinity 2.8.4, this error has cropped up several times for my students. The general advice is not super, but to reduce the number of CPUs your using. So, specifically for you, I'd start the assembly up again, using the exact same command, except for that I would change `CPU=16` to `CPU=8`. This will prolong the assembly process a bit, but hopefully it will finish successfully. @brianjohnhaas any other suggestions?
