### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by santiagorevale** [macmanes-lab/Oyster_River_Protocol#15]
Hi Matthew,

I've seen your paper regarding ORP. I have a couple of questions that maybe you could answer:

1) have you compared the results of ORP by using the latest version of Trinity (2.8.4) instead of the older one (2.4.0) reported in the paper?

2) I've noticed you replaced Shannon for TransAbyss, is that an equivalent replacement? I mean, do they behave similarly? Or have you just done a replacement to keep the number of assemblies to 4?

3) is it possible to run the complete pipeline having independent jobs to run in parallel? If not, have you thought about writing the pipeline in [NextFlow](https://www.nextflow.io/)?

Thank you very much for your help.

Cheers,
Santiago

**Comment by macmanes** [comment]
Hi, 

1. I compared, and found the same qualitative results. Of note, Trinity is installed via conda. As of today, 2.8.4 is the version installed. 

2. Yes. Replaced! It's not that they behave so similarly, but instead that TransABySS actually finished, and does not use *crazy* amounts of RAM. Tho Shannon did perform well when we could get it to finish, for something like 50% of datasets would hang, or use >512Gb of RAM, which is too much. TransABySS frankly does not have some of the good properties of Shannon, but at least it is not a barrier. 

3. Do you mean run the 4 assemblies in parallel, at the same time? If so, yes, in theory that can happen. You'd add the `-j` flag to the command. So, `-j 4` for 4 parallel jobs. *BUT* I will say that I have not tested this, and it may not work at the moment. In fact, it most surely will not work. Let me know if this is something critical to your workflow and I can work on it.
