### ISSUE TITLE
Verifying transaction: failed

### ISSUE THREAD

**Issue by rafaeltiveron** [macmanes-lab/Oyster_River_Protocol#19]
When "make":

```
Preparing transaction: done
Verifying transaction: failed

PaddingError: Placeholder of length '80' too short in package /root/Downloads/Oyster_River_Protocol-2.1.0/software/anaconda/install/envs/orp_v2/bin/Rscript.
The package must be rebuilt with conda-build > 2.0.

Makefile:44: recipe for target 'orp_v2' failed
make: *** [orp_v2] Error 1
```

**Comment by rafaeltiveron** [comment]
Sorry, I was trying to dowload into ~/Downloads/Oyster_River_Protocol..., generating long phrase characters. I'll try to reduce and lets see if it is resolved. I'll come back.

**Comment by rafaeltiveron** [comment]
Yes. This was the error cause. I would like to inform more two messages showed during installation, maybe important for 100% compilation of packages used in ORP:

`DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.`

`deeploc 0.1 requires Theano==1.0.1, which is not installed.`

**Comment by macmanes** [comment]
thanks! Right now there are a few things that depend on Py2.7.. Will have to address soon!
