### ISSUE TITLE
split-paired-reads.py version

### ISSUE THREAD

**Issue by peterdfields** [macmanes-lab/Oyster_River_Protocol#2]
I was just wondering which version of khmer the split-paired-reads.py derives from in this protocol, given when I try the most recent khmer from pip I keep running into issues with unrecognized paired reads in the corrected, interleaved fastq files (either when using rcorrector or bfc).

**Comment by macmanes** [comment]
Hi @peterdfields, this is khmer version 2.0 and thanks, I should add version numbers to the protocol in the relevant places!  What does the error message look like, and how is is the fastQ header formatted? cc: @ctb

**Comment by peterdfields** [comment]
So the error message is as follows:

Unpaired reads found starting at HWI-ST974:109:C0W6RACXX:8:1113:15474:50653     ec:Z:0_0:2_0_1:0_0; exiting

The read files, following correction, look like the following:

@HWI-ST974:109:C0W6RACXX:8:1113:15474:50653     ec:Z:0_0:2_0_1:0_0
TTTAGATGCAGCTGTTTGGGcGGCCAACCCTAGAGCAGTTGCAGGCAATCCTTCAATTTCTTTCTTGTC
+
????????????????????%???????????????????????????????????+??+?????????
@HWI-ST974:109:C0W6RACXX:8:1113:15474:50653     ec:Z:0_0:1_0_0:0_0
GTTGAGTGAGGCTCGAAAACGGATTGTTGAAAATCAACTTAAGGAGGCTGTTCTCAGTGGTGTTTCTCT
+
????????????????????????????????????????????????+??????+???++++++++++
@HWI-ST261:376:AD0D1MABXX:1:46:4033:54388       ec:Z:0_0:1_0_0:0_0
GGTCAAGCCCTTAAGTGAGGGAGAGAATGAAGCATTGCTGCACTCAAATCTTACTTGCTTCAAGTGCGACGTAACAAGATGTGTGATGCCTTC
+
????????????????????????????????????????????????????????????????????????????????????????+????
@HWI-ST261:376:AD0D1MABXX:1:46:4033:54388       ec:Z:0_0:1_0_0:0_0
ATTAGAATGAGTATCCTCAAGAAGAACGTTAATTAATCTCATTTGAAGGCATCACACATCTTGTTACGTCGCACTTGAAGCAAGTAAGATTTG
+
?????????????????????????????????????????????????????????????????????????????????????????????

**Comment by macmanes** [comment]
er, this is IMO annoying behavior from @lh3's  BFC, stripping off the left and right designations.  See https://github.com/lh3/bfc/issues/8 

try this

```
sed 's_ _/1 _g' file.1.fq > edited_file.1.fq
```

and this for the /2 file

```
sed 's_ _/2 _g' file.2.fq > edited_file.2.fq
```

this should restore the proper behavior, and I'm guessing that at some point khmer will be able to figure this out on its own.

**Comment by peterdfields** [comment]
I'll give it a shot. Thanks for your advice!

**Comment by peterdfields** [comment]
wait, I'm not sure I understand how this works with the resultant bfc.corr.fq file that needs to be split.

**Comment by macmanes** [comment]
doh! Right.. I'll get you a fix shortly. How many read pairs are you correcting?

**Comment by peterdfields** [comment]
Just at 20 million, that's why I went with the bfc route instead of Rcorrector (based upon the advice in the protocol).

**Comment by macmanes** [comment]
ok.. so there are 2 options.. One is to put the /1 and /2 on your reads before interleaving (I assume these are Illumina 1.8, with the pairs originally designated by 1: and 2:). Those `sed` commands from above should work for that. 

Option 2 is to correct the /1 and /2 separately, but I don't think this is your best option. 

Lastly. you could use RCorrector. If you look at Fig 2 here - http://biorxiv.org/content/biorxiv/early/2015/12/30/035642.full.pdf, there is very little difference between the 2 error corrections at 20M pairs, though bfc is better.   

Thanks for pointing out these issue! For all the testing, I used reads from the SRA, which designated pairs the 'old fashioned' way..

**Comment by peterdfields** [comment]
Okay sounds good. Thanks again for your help, Matt.
