### ISSUE TITLE
Protocol textual error

### ISSUE THREAD

**Issue by peterdfields** [macmanes-lab/Oyster_River_Protocol#3]
In the protocol the Salmon index is named salmon.idx, as in:

~/salmon-0.5.1/bin/salmon index -t Rcorr_trinity.Trinity.fasta -i salmon.idx --type quasi -k 31

The quantification step is using an index called transcripts2_index, as in:

~/salmon-0.5.1/bin/salmon quant -p 32 -i transcripts2_index -l MSR -1 file_1.cor.fastq -2 file_2.cor.fastq -o salmon_orig

I assume this needs to be changed to salmon.idx.

**Comment by macmanes** [comment]
Thanks @peterdfields for catching that. It has been changed.
