### ISSUE TITLE
sampledata test failed

### ISSUE THREAD

**Issue by RyosukeKakehashi** [macmanes-lab/Oyster_River_Protocol#43]
Hi,

I recently installed ORP v2.3.1 via manually constructed conda environment (according to yml file) and Makefile.
I tried to run sampledata without TPM_FILT option, and finished as follows:

---------------------------------------------------------------------------------------------------------------------------------------
*****  QUALITY REPORT FOR: test using the ORP version 2.3.1 ****
*****  THE ASSEMBLY CAN BE FOUND HERE: /home/ryosuke/Oyster_River_Protocol/sampledata/assemblies/test.ORP.fasta **** 

*****  BUSCO SCORE ~~~~~~~~~~~~~~~~~~~~~~>	C:0.0%[S:0.0%,D:0.0%],F:0.0%,M:100.0%,n:255	   
*****  TRANSRATE SCORE ~~~~~~~~~~~~~~~~~~>      0.3972
*****  TRANSRATE OPTIMAL SCORE ~~~~~~~~~~>      0.54134
*****  UNIQUE GENES ORP ~~~~~~~~~~~~~~~~~>      16
*****  UNIQUE GENES TRINITY ~~~~~~~~~~~~~>      16
*****  UNIQUE GENES SPADES55 ~~~~~~~~~~~~>      16
*****  UNIQUE GENES SPADES75 ~~~~~~~~~~~~>      13
*****  UNIQUE GENES TRANSABYSS ~~~~~~~~~~>      15
*****  READS MAPPED AS PROPER PAIRS ~~~~~>      99.30%
---------------------------------------------------------------------------------------------------------------------------------------

However, I ran sampledata with TPM_FILT (=0.2 or 1) option, and got error as follows:

---------------------------------------------------------------------------------------------------------------------------------------
make: *** [/home/ryosuke/Oyster_River_Protocol/oyster.mk:369: /home/ryosuke/Oyster_River_Protocol/sampledata/assemblies/test.ORP.fasta] Error 1
---------------------------------------------------------------------------------------------------------------------------------------

I checked the assemblies/working directory, and found that there is no test.donotremove.list file. I also checked test.blasted file. The test.blasted existed, but no output there.

Is this result normal?

Thank you in advance!

**Comment by macmanes** [comment]
Yes there is a bug in the software that I need to fix. When you set a TPM filter but there are no genes being expressed below this threshold, the program errors. This should not be a problem in “real” data but is a problem in the test. I'm planing on fixing this bug ASAP.

Thanks,
Matt

On Apr 2, 2021, at 04:58, RyosukeKakehashi ***@***.******@***.***>> wrote:

Caution - External Email




Hi,

I recently installed ORP v2.3.1 via manually constructed conda environment (according to yml file) and Makefile.
I tried to run sampledata without TPM_FILT option, and finished as follows:

________________________________

***** QUALITY REPORT FOR: test using the ORP version 2.3.1 ****
***** THE ASSEMBLY CAN BE FOUND HERE: /home/ryosuke/Oyster_River_Protocol/sampledata/assemblies/test.ORP.fasta ****

***** BUSCO SCORE ~~~~~~~~~~~~~~~~~~~~~~> C:0.0%[S:0.0%,D:0.0%],F:0.0%,M:100.0%,n:255
***** TRANSRATE SCORE ~~~~~~~~~~~~~~~~~~> 0.3972
***** TRANSRATE OPTIMAL SCORE ~~~~~~~~~~> 0.54134
***** UNIQUE GENES ORP ~~~~~~~~~~~~~~~~~> 16
***** UNIQUE GENES TRINITY ~~~~~~~~~~~~~> 16
***** UNIQUE GENES SPADES55 ~~~~~~~~~~~~> 16
***** UNIQUE GENES SPADES75 ~~~~~~~~~~~~> 13
***** UNIQUE GENES TRANSABYSS ~~~~~~~~~~> 15
***** READS MAPPED AS PROPER PAIRS ~~~~~> 99.30%

However, I ran sampledata with TPM_FILT (=0.2 or 1) option, and got error as follows:

________________________________
make: *** [/home/ryosuke/Oyster_River_Protocol/oyster.mk:369: /home/ryosuke/Oyster_River_Protocol/sampledata/assemblies/test.ORP.fasta] Error 1

I checked the assemblies/working directory, and found that there is no test.donotremove.list file. I also checked test.blasted file. The test.blasted existed, but no output there.

Is this result normal?

Thank you in advance!

**Comment by RyosukeKakehashi** [comment]
I feel relieved to hear that!
Thank you for your reply.
