### ISSUE TITLE
TransRate-ORP: Which modifications were made?

### ISSUE THREAD

**Issue by lmuenter** [macmanes-lab/Oyster_River_Protocol#46]
Hi,

sadly, [`TransRate`](https://github.com/blahah/transrate) is abandonware now. The packaged version of the ORP however is so handy that I rely heavily on it (Thank you for packaging `TransRate`!). It runs reliably and without any issues. I have one question though: in your [publication](https://peerj.com/articles/5428/) you mention, that `TransRate-ORP` has been modified. What kinds of modifications have been made?
Thank you,

Lukas

**Comment by macmanes** [comment]
only to use a more updated version of Salmon. And to fix the various bugs that prevent it from being run "natively"

**Comment by lmuenter** [comment]
Very cool, thanks for this!
