### ISSUE TITLE
make error -- software/anaconda/install/bin/conda: No such file or directory

### ISSUE THREAD

**Issue by jfordonez** [macmanes-lab/Oyster_River_Protocol#7]
this prints out after the make:

/bin/bash: /home/mmeel/Bioinfo_software/Oyster_River_Protocol/software/anaconda/install/bin/conda: No such file or directory
/bin/bash: /home/mmeel/Bioinfo_software/Oyster_River_Protocol/software/anaconda/install/bin/conda: No such file or directory
cd /home/mmeel/Bioinfo_software/Oyster_River_Protocol/software/anaconda && curl -LO https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Received HTTP code 404 from proxy after CONNECT
Makefile:36: recipe for target 'conda' failed
make: *** [conda] Error 56

I have miniconda installed; is it possible to use it instead? Thanks!

**Comment by jfordonez** [comment]
Yes. Thank you!

Apparently, I just had to disable the proxy to make it work. Sorry!

**Comment by macmanes** [comment]
no worries! Please let me know if you have other issues!
